window.INCIDENTS = [
  {
    id: "geelong",
    continent: "Oceania",
    lng: 144.36,
    lat: -38.14,
    title: "Viva Energy refinery fire",
    subtitle: "Geelong, Victoria, Australia",
    date: "April 16, 2026",
    description: "Al Jazeera reported a gas leak ignited a fire at Viva Energy's Geelong refinery, a major Australian fuel supplier.",
    url: "https://www.aljazeera.com/news/2026/4/16/fire-breaks-out-at-crucial-australian-refinery-raising-fuel-supply-fears",
    color: "#ff6a3d"
  },
  {
    id: "port-arthur",
    continent: "North America",
    lng: -93.9718,
    lat: 29.8608,
    title: "Valero refinery explosion",
    subtitle: "Port Arthur, Texas, United States",
    date: "March 24, 2026",
    description: "France 24 reported an oil refinery explosion in Texas. The marker is placed at Valero's Port Arthur refinery, the location identified in contemporaneous coverage.",
    url: "https://www.france24.com/en/video/20260324-oil-refinery-explosion-reported-in-texas",
    color: "#ffd166"
  },
  {
    id: "dos-bocas",
    continent: "North America",
    lng: -93.204,
    lat: 18.4187,
    title: "Second fire at Olmeca refinery",
    subtitle: "Dos Bocas, Tabasco, Mexico",
    date: "April 9, 2026",
    description: "The Chemical Engineer reported a second fire in two months at Mexico's newest refinery, also known as Dos Bocas or Olmeca.",
    url: "https://www.thechemicalengineer.com/news/no-injuries-following-second-fire-in-two-months-at-mexico-s-newest-refinery/",
    color: "#7dd3ff"
  },
  {
    id: "esmeraldas",
    continent: "South America",
    lng: -79.6539,
    lat: 0.9592,
    title: "Fire at Ecuador's biggest refinery",
    subtitle: "Esmeraldas, Ecuador",
    date: "March 2, 2026",
    description: "OilPrice reported a fire at Petroecuador's 110,000 bpd Esmeraldas refinery, forcing a temporary halt in operations.",
    url: "https://oilprice.com/Latest-Energy-News/World-News/Fire-Disrupts-Operations-at-Ecuadors-Biggest-Refinery.html",
    color: "#ff8f5a"
  },
  {
    id: "pasadena-bayport",
    continent: "North America",
    lng: -95.0415,
    lat: 29.6225,
    title: "Bayport-area chemical plant flare",
    subtitle: "Pasadena, Texas, United States",
    date: "March 25, 2026",
    description: "ABC13 reported heavy smoke and a bright flare at LyondellBasell's Pasadena plant near Bayport after operational issues triggered flaring.",
    url: "https://abc13.com/post/whats-smoking-pasadena-lyondellbasell-working-stop-bright-flare-bayport-area-chemical-plant-company-says/18772702/",
    color: "#ffb347"
  },
  {
    id: "primorsk-port",
    continent: "Europe",
    lng: 28.74,
    lat: 60.37,
    title: "Strike on Russian oil port near Finland",
    subtitle: "Primorsk, Leningrad Oblast, Russia",
    date: "March 23, 2026",
    description: "France 24 reported a Ukrainian strike on a major Russian oil port near Finland. This marker is placed at Primorsk, the Baltic export terminal referenced in contemporaneous coverage.",
    url: "https://www.france24.com/en/live-news/20260323-ukraine-hits-major-russian-oil-port-near-finland",
    color: "#9cc9ff"
  },
  {
    id: "mumbai-high-shp",
    continent: "Asia",
    lng: 71.35,
    lat: 19.45,
    title: "Fire on Mumbai High SHP platform",
    subtitle: "Mumbai High field, Arabian Sea, India",
    date: "April 6, 2026",
    description: "Offshore Energy reported a fire on ONGC's SHP platform in the Mumbai High asset. The marker uses an approximate offshore field location.",
    url: "https://www.offshore-energy.biz/ten-workers-suffer-injuries-as-fire-breaks-out-at-asian-offshore-oil-platform/",
    color: "#5ad1ff"
  },
  {
    id: "filanovsky",
    continent: "Asia",
    lng: 49.15,
    lat: 44.15,
    title: "Attack on Filanovsky oil platform",
    subtitle: "Filanovsky field, Caspian Sea, Russia",
    date: "December 11, 2025",
    description: "Anews.az reported a strike on LUKOIL's Filanovsky offshore platform in the Caspian Sea. The marker uses an approximate offshore field position.",
    url: "https://anews.az/en/world/498955/ukraine-hits-russian-oil-platform-in-the-caspian-sea-for-the-first-time/",
    color: "#7de0d6"
  },
  {
    id: "bhilai-steel",
    continent: "Asia",
    lng: 81.3509,
    lat: 21.1938,
    title: "Fire in Bhilai Steel Plant turbine unit",
    subtitle: "Bhilai, Chhattisgarh, India",
    date: "April 7, 2026",
    description: "The Times of India reported that seven workers were injured after a fire broke out in the STG-4 turbine unit at Bhilai Steel Plant.",
    url: "https://timesofindia.indiatimes.com/city/raipur/seven-suffer-burns-as-fire-breaks-out-in-bhilai-steel-plant-turbine-unit/articleshow/130085953.cms",
    color: "#ff7f7f"
  },
  {
    id: "singhitarai-vedanta",
    continent: "Asia",
    lng: 82.94,
    lat: 22.02,
    title: "Vedanta power plant blast",
    subtitle: "Singhitarai village, Sakti district, India",
    date: "April 14, 2026",
    description: "NDTV reported the blast at Vedanta's thermal power plant in Singhitarai village, where the death toll later climbed to 24.",
    url: "https://www.ndtv.com/india-news/death-count-in-chhattisgarh-vedanta-power-plant-blast-climbs-to-24-11378417",
    color: "#ff5f6d"
  },
  {
    id: "south-pars-asaluyeh",
    continent: "Asia",
    lng: 52.62,
    lat: 27.48,
    title: "South Pars field and Asaluyeh attack",
    subtitle: "South Pars and Asaluyeh, Iran",
    date: "March 18, 2026",
    description: "Wikipedia summarizes strikes on the South Pars gas field and Asaluyeh facilities that damaged pipelines and halted output at two refineries.",
    url: "https://en.wikipedia.org/wiki/2026_South_Pars_field_attack",
    color: "#ff8a80"
  },
  {
    id: "ras-laffan-qatar",
    continent: "Asia",
    lng: 51.55,
    lat: 25.92,
    title: "Ras Laffan LNG facilities damaged",
    subtitle: "Ras Laffan Industrial City, Qatar",
    date: "March 19, 2026",
    description: "Reuters reported that Iranian attacks damaged two LNG trains and a GTL facility in Ras Laffan, taking about 17% of Qatar's LNG export capacity offline for years.",
    url: "https://www.reuters.com/business/energy/iran-attack-damage-wipes-out-17-qatars-lng-capacity-three-five-years-qatarenergy-2026-03-19/",
    color: "#8bd3ff"
  },
  {
    id: "yanbu-samref",
    continent: "Asia",
    lng: 38.06,
    lat: 24.09,
    title: "Drone strike at Samref refinery",
    subtitle: "Yanbu, Saudi Arabia",
    date: "March 19, 2026",
    description: "Arab News reported that a drone hit the Samref refinery in Yanbu on Saudi Arabia's Red Sea coast while a ballistic missile aimed at Yanbu port was intercepted.",
    url: "https://www.arabnews.com/node/2636933/saudi-arabia",
    color: "#ffd479"
  },
  {
    id: "strait-of-hormuz",
    continent: "Asia",
    lng: 56.25,
    lat: 26.55,
    title: "Strait of Hormuz crisis",
    subtitle: "Strait of Hormuz, Persian Gulf and Gulf of Oman",
    date: "February 28, 2026",
    description: "Wikipedia describes the 2026 Strait of Hormuz crisis as a major blockade and ship-attack campaign that disrupted one of the world's most important energy chokepoints.",
    url: "https://en.wikipedia.org/wiki/2026_Strait_of_Hormuz_crisis",
    color: "#c6a6ff"
  },
  {
    id: "rajasthan-refinery",
    continent: "Asia",
    lng: 72.24,
    lat: 25.92,
    title: "Fire at Rajasthan refinery",
    subtitle: "Pachpadra-Barmer area, Rajasthan, India",
    date: "April 20, 2026",
    description: "Reuters reported a fire at a refinery in Rajasthan. This marker is placed at the Barmer refinery complex near Pachpadra, the state flagship refining project referenced in contemporaneous coverage.",
    url: "https://www.reuters.com/world/india/fire-breaks-out-refinery-indias-rajasthan-local-media-reports-2026-04-20/",
    color: "#ffa36c"
  },
  {
    id: "etoile-texas",
    continent: "North America",
    lng: -94.41,
    lat: 31.38,
    title: "Oil and gas site explosion near Etoile",
    subtitle: "Etoile, Nacogdoches County, Texas, United States",
    date: "April 21, 2026",
    description: "Houston Public Media reported an explosion and fire at an oil and gas site near Etoile that prompted evacuations in Nacogdoches County.",
    url: "https://www.houstonpublicmedia.org/articles/news/public-safety/2026/04/21/549647/nacogdoches-explosion-etoile-oil-gas-fire-evacuation/",
    color: "#ffcf6d"
  },
  {
    id: "bucharest-thermal-plant",
    continent: "Europe",
    lng: 26.1,
    lat: 44.43,
    title: "Explosion at Bucharest thermal power plant",
    subtitle: "Bucharest, Romania",
    date: "April 21, 2026",
    description: "ILKHA reported an explosion at a thermal power plant in Bucharest that injured workers and triggered an emergency response.",
    url: "https://ilkha.com/english/world/romania-explosion-hits-thermal-power-plant-in-bucharest-527102",
    color: "#8fd8ff"
  },
  {
    id: "tuapse-oil-port",
    continent: "Europe",
    lng: 38.99,
    lat: 44.1,
    title: "Drone strike near Tuapse oil port",
    subtitle: "Tuapse, Krasnodar Krai, Russia",
    date: "March 14, 2025",
    description: "RFE/RL reported Ukrainian drone strikes in and around Tuapse, home to a major Black Sea oil port and refinery complex.",
    url: "https://www.rferl.org/a/ukraine-russia-drone-strikes-tuapse/33736220.html",
    color: "#8ab6ff"
  },
  {
    id: "haripur-pipeline",
    continent: "Asia",
    lng: 72.89,
    lat: 33.82,
    title: "Gas pipeline explosion in Haripur",
    subtitle: "Hattar Industrial Estate, Haripur district, Pakistan",
    date: "April 17, 2026",
    description: "The Times of India reported that a gas pipeline explosion at Hattar Industrial Estate in Khyber Pakhtunkhwa triggered a massive fire and killed at least eight people.",
    url: "https://timesofindia.indiatimes.com/world/pakistan/eight-killed-as-gas-pipeline-explodes-in-pakistans-khyber-pakhtunkhwa/articleshow/130317757.cms",
    color: "#ff936e"
  },
  {
    id: "homalin-port",
    continent: "Asia",
    lng: 94.91,
    lat: 24.87,
    title: "Fuel tanker blast at Myanmar port",
    subtitle: "Homalin, Sagaing Region, Myanmar",
    date: "April 21, 2026",
    description: "Reporting carried by Yahoo said at least two people were killed and others injured after an oil tanker caught fire during fuel transfer at the port of Homalin.",
    url: "https://www.yahoo.com/news/articles/least-two-dead-myanmar-port-082221755.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAGWO4GawrHJXiD23TkbSblzU2sjy6q77-F90AExGHniNGaFzfFpgNtrDIlJhYEhTf2G0QdSskf6JrkgMyUyu2nN5ZjfPAPbuyGCC_2DI6cbUj2v33-Wh1mekm1F7DrJYuaM1iNn_SPobwFBoCw36yRw2912GeLs5CqbayZXMs8br",
    color: "#7ad7ff"
  }
];
